modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mscreator"
version="1.0.0"
displayName="MSCreator"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="User, MCreator"

[[dependencies.mscreator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




